### ISSUE TITLE
Safari compat fixes

### ISSUE THREAD

**Issue by DirtyHairy** [6502ts/6502.ts#24]
Safaris indexedDB implementation is known to be badly broken -> fix by selectively enabling a shim in safari.

**Comment by mschroeder** [comment]
IndexedDB does not seem to be a problem in Safari 10 (also in WebWorkers), so I suggest to close this issue.

**Comment by mschroeder** [comment]
After further investigation, there still exist problems with IndexedDB and Dexie.js in Safari.

**Comment by DirtyHairy** [comment]
This [shim](https://github.com/axemclion/IndexedDBShim) should fix the issue. However, skimming the issue tracker suggests that getting this to work selectively in Safari might be tricky.

**Comment by DirtyHairy** [comment]
Works fine in Safari 11.
