### ISSUE TITLE
Loading zipped ROMs from the Stellerator window

### ISSUE THREAD

**Issue by sa666666** [6502ts/6502.ts#43]
As you know, we often test ROMs in Stella and Stellerator, and when uploading the ROMs to git, they need to be zipped.  Stella already supports loading zipped ROMs; it would be much easier if Stellerator did too.

**Comment by mschroeder** [comment]
@DirtyHairy, https://gildas-lormeau.github.io/zip.js/ looks most promising to achieve this.

**Comment by DirtyHairy** [comment]
@mschroeder Either that or [adm-zip](https://github.com/cthackers/adm-zip). adm-zip looks pretty much dead, but it is available from NPM and will integrate neatly into the build workflow. zip.js does not smell like a dead fish yet and looks more modern and performant, but must be loaded globally :smile: At the moment, I am leaning towards adm-zip.

**Comment by DirtyHairy** [comment]
@sa666666 I have found myself missing this lately, too. I'll see what we can whip up.

**Comment by DirtyHairy** [comment]
I think the most sensible way to do this is putting an upper limit on zip file size and offering a dialog with a dropdown to select one of the files inside the zip.

**Comment by DirtyHairy** [comment]
Opening ROMs directly from ZIPs is now implemented (and deployed to github.io :smirk:). ZIPs with multiple ROMs are handled by selecting a ROM from a dialog.
