### ISSUE TITLE
Investigate low level TIA audio emulation

### ISSUE THREAD

**Issue by DirtyHairy** [6502ts/6502.ts#49]
Stella's new-sound branch contains a low level simulation of TIA audio generation written by Chris Brenner. This could be ported and adapted once we have #44 done.

**Comment by sa666666** [comment]
Yes, I am very interested in progress on this, both in Stellerator and Stella.  The code in that branch is actually from C code directly from an FPGA designed by Chris Brenner (crispy on AtariAge).  As such, it has been tested as real hardware, and is quite accurate.

I have test ROMs, descriptions, generated AIFF and RAW sound data, etc for this.  IOW, when the time comes, we have quite a bit of stuff ready for testing.
