### ISSUE TITLE
0840 bankswitching support

### ISSUE THREAD

**Issue by ale-79** [6502ts/6502.ts#66]
The "Toyshop Trouble" PAL60 rom has just been posted on AA ([http://atariage.com/forums/topic/273291-pal-version-of-toyshop-trouble/#entry3916621](http://atariage.com/forums/topic/273291-pal-version-of-toyshop-trouble/#entry3916621)) and I noticed that stellerator doesn't support its bankswitching scheme (0840). 
I don't know of other games utilizing that (The NTSC rom that was released a few years ago uses the classic F8 scheme)

Here are some info:
[http://atariage.com/forums/blog/142/entry-2282-econobanking/](http://atariage.com/forums/blog/142/entry-2282-econobanking/)

**Comment by DirtyHairy** [comment]
Thanks a lot, Alex, I'll add support these days --- suits the holiday theme :)

**Comment by DirtyHairy** [comment]
Fixed and published :) Thanks again.
